services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    container_name: nlw-agents-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlw_agents
    ports:
      - "5433:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql